version: "3.8"


services:

  #################################
  # Profile microservice (Simple)
  #################################
  # profile:
  #   image: mosengtim2021/profile:1.0
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/profile


  #################################
  # Crop Management (Simple)
  #################################
  # crop_management:
  #   image: mosengtim2021/crop_management:1.0
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/cropmanagement


  ###############################################
  # Inventory (Simple)
  ###############################################
  inventory:
    build:
      context: ./inventory
      dockerfile: dockerfile
    image: wuhao2021/inventory:1.0
    restart: always
    environment:
      inventory_URL: mysql+mysqlconnector://is213@host.docker.internal:3306/inventory
      PYTHONUNBUFFERED: 1

  ###############################################
  # Machine learning (Simple)
  ###############################################
  # machine_learning:
  #   image: mosengtim2021/machine_learning:1.0
  #   depends_on:
  #     - profile
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/machine_learning

  ###############################################
  # Purchase Activity (Complex)
  ###############################################
  # purchase_activity:
  #   image: mosengtim2021/purchase_activity:1.0
  #   depends_on:
  #     - profile
  #   environment:
  #     purchase_request_URL: mysql+mysqlconnector://is213@host.docker.internal:3306/purchase_activity

  ###############################################
  # Inventory Manager (Complex)
  ###############################################
  inventory_manager:
    build:
      context: ./InventoryManager
      dockerfile: dockerfile
    image: wuhao2021/inventory_manager:1.0
    depends_on:
      - inventory
    environment:
      inventory_manager_URL: mysql+mysqlconnector://is213@host.docker.internal:3306/inventory_manager
      PYTHONUNBUFFERED: 1