FROM python:3-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY ./profile.py .
CMD [ "python", "./profile.py" ]
COPY ./invokes.py ./test_invoke_http.py ./d