FROM python:3-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY ./inventory_manager.py ./invokes.py ./
CMD [ "python", "./inventory_manager.py" ]