# Base image
FROM node:14-alpine

# Create a working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the source code to the container
COPY . .

# Expose the port used by the application
EXPOSE 5010

# Start the server
CMD ["npm", "start"]
