FROM python:3-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY ./purchase_activity.py ./amqp_setup.py ./invokes.py ./send_sms.py ./
CMD [ "python", "./purchase_activity.py" ]
