FROM python:3-slim
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN python -m pip install --no-cache-dir -r requirements.txt
COPY ./server.py ./public/checkout.css ./public/checkout.html ./public/checkout.js ./public/logo.png ./public/stripe.png ./public/success.html
CMD [ "python", "./server.py" ]
